### ISSUE TITLE
Cotw

### ISSUE THREAD

**Issue by Red-destroyer53** [janstehno/cotwcompanion#23]
Don't know if it's part of the story mode quest on the Spanish map but when I was hunting the murderous wolf in the monument It started running into a gate so I took my time to try and get a heart shot but after a while it ran through the gate at lightning speed and I had to chase it across the map for about 15-20 minutes to finally shoot it. Is it part of the quest? If not will it be fixed?

**Comment by janstehno** [comment]
This is GitHub storage and Issue list for the app COTW Companion on mobile devices. Definitely not for the game. I am sorry but I will have to close and delete this as it has to do nothing with the app.
