### ISSUE TITLE
Animals - detail information card for Great Ones while imperial system is on won't load

### ISSUE THREAD

**Issue by DraconicAlpha** [janstehno/cotwcompanion#31]
Can't see any great one animal species it won't load.

**Comment by janstehno** [comment]
If this is an app issue, I would need much more information. If it is a game issue, I have no control over it and this will be closed and deleted.

**Comment by DraconicAlpha** [comment]
When trying to look at any of the animals species that have a great one variant it says this so its an app problem all other animals don't show this only the specific ones with a great one.Sent from my Verizon, Samsung Galaxy smartphone
-------- Original message --------From: Jan Stehno ***@***.***> Date: 11/21/23  7:40 PM  (GMT-05:00) To: janstehno/cotwcompanion ***@***.***> Cc: DraconicAlpha ***@***.***>, Author ***@***.***> Subject: Re: [janstehno/cotwcompanion] Great ones (Issue #31) 
If this is an app issue, I would need much more information. If it is a game issue, I have no control over it and this will be closed and deleted.

**Comment by janstehno** [comment]
I amsorry, but I am so confused. What are you reffering to by saying `this`? And where exactly are you seeing this problem. You can always share a screenshot so I can find the problem and solution easier.

**Comment by DraconicAlpha** [comment]
When you go to click on any animal with a great one it shows that image. You dont get any information abou the animal like you normaly would. If you click on black bear,mosse,whitetail deer,red dear or falow deer thag screen shows up. You don't see the time for zones or anything else.Sent from my Verizon, Samsung Galaxy smartphone
-------- Original message --------From: Jan Stehno ***@***.***> Date: 11/22/23  4:13 AM  (GMT-05:00) To: janstehno/cotwcompanion ***@***.***> Cc: DraconicAlpha ***@***.***>, Author ***@***.***> Subject: Re: [janstehno/cotwcompanion] Great ones (Issue #31) 
I am sorry, but I am so confused. What are you reffering to by saying this? And where exactly are you seeing this problem. You can always share a screenshot so I can find the problem and solution easier.

**Comment by janstehno** [comment]
I am sorry but I still don't understand so I really need the screenshots. You can also try to describe your problem in your native language if it is not English. I am really trying to help, but this is just not clear for me. Therefor this issue could be closed and deleted for lack of information.

**Comment by DraconicAlpha** [comment]
So the screen ahot isn't loading because i have sent the a screenschoots
with it when i send.

**Comment by janstehno** [comment]
I see, you are using email to respond to me. Probably the reason why it does not work. Rather go here: https://github.com/janstehno/cotwcompanion/issues/31 and post the reply with the screenshots as another comment to the issue.

**Comment by janstehno** [comment]
Great, now I can see it. Interesting, there is indeed an issue. So it appears when you have an imperial system and want to see detailed information card with a great one animal? If so, then this is enough for me to find the problem and solve it. For now, please, use metric system until I release an update.

**Comment by DraconicAlpha** [comment]
Ok thank you and sorry for the confusion

**Comment by janstehno** [comment]
No worries, I already found the issue and solved it on my side. Now I just have to release an update. I don't know when it will be available.

**Comment by DraconicAlpha** [comment]
Ok thank you so much have a great day
