### ISSUE TITLE
Whitetail deer bug

### ISSUE THREAD

**Issue by ckbales** [janstehno/cotwcompanion#32]
When checking zone information on Whitetail deer 🦌 an error code is thrown. 

FormatException: invalid radix -10 number (at character 1) 0lb<

**Comment by janstehno** [comment]
Which zone information? Like in the Need zones feature, or in the animal information card, or on the map? You can also attach a screenshot, so I can find the problem and solution easier.

**Comment by janstehno** [comment]
Alright, so it seems like you are reffering to the same issue as we already discussed here https://github.com/janstehno/cotwcompanion/issues/31 . I will therefor close and delete this one as it is a duplicate. Thank you for sharing the issue.
