### ISSUE TITLE
Map issue

### ISSUE THREAD

**Issue by Aggressor356** [janstehno/cotwcompanion#35]
The new map system on this app doesn't properly show all the animal need zones.

**Comment by janstehno** [comment]
What exactly do you mean? If you have performance mode on, it approximates general positions based on need zones (collected by me). If you don't have performance mode on, it shows the need zones (again collected by me).

The app clearly says the need zones are not completed, that you should use them as a guide only, and that they will definitely not be accurate or same as yours.

**Comment by janstehno** [comment]
As there is a lack of information on this issue, I will close and delete it.
