### ISSUE TITLE
New error loadind app

### ISSUE THREAD

**Issue by Knightironclad** [janstehno/cotwcompanion#49]
during the load up the app shows an error in any  section i cant check maps animals weapons or anything im using a motorola g9 power thanka for your work hope you can fix it soon

**Comment by BeckMcKim** [comment]
Unfortunately I am also having this issue. I just downloaded this app onto my Samsung S22, and it won't allow me to open the reserves, wildlife, weapons, or callers section. I have found a work around by going to the tools sections, however. If I did this properly, a screenshot of the error it gives me will be attached; it's the same for each section. 
![Screenshot_20231230_021613](https://github.com/janstehno/cotwcompanion/assets/155225045/45539560-88f7-466f-bce2-2a2ac20f6fd9)

**Comment by janstehno** [comment]
It has been fixed on my side. The update should be downloadable at 11 am.
