### ISSUE TITLE
Wrong classed animal

### ISSUE THREAD

**Issue by Ratim164** [janstehno/cotwcompanion#65]
Your app say that the feral goat is class 5, but on the map Emerald coast, the goat Is a class 3 Animal.

**Comment by janstehno** [comment]
Hey, yeah that is misinformation on my side. I accidentally edited Feral Goat instead of Feral Pig. This should be fixed in the next update. Thank you for noticing anyway.

**Comment by Ratim164** [comment]
You're welcome my Czech bro
